### ISSUE TITLE
QDT temporary files left in tmp directory

### ISSUE THREAD

**Issue by Chert-Nik** [ispras/qdt#26]
I found this problem while working on this issue #20

In some cases if the device tree is not successfully built, the files from qdt work remain in the tmp folder.
There will be folder in tmp directory with name similar to
qdt-qemu-131b9a05705636086699df15d4a6d328bb2585e8-aybrz14l
the size of which can exceed one gigabyte.

It seems like you need to make some kind of a callback that will clear the qdt files of the tmp folder in case of a crash.

**Comment by BDanAnd** [comment]
#27 solves this problem
